---
- hosts: jenkins_slave
  become: true
  tasks:
  - name: update the system
    apt:
      update_cache: yes
      cache_valid_time: 3600
  - name: download and install java 17
    apt:
      name: openjdk-17-jre
      state: present
  - name: download maven packages
    get_url:
      url: https://dlcdn.apache.org/maven/maven-3/3.9.4/binaries/apache-maven-3.9.4-bin.tar.gz
      dest: /opt
  - name: extract it
    unarchive:
      src: /opt/apache-maven-3.9.4-bin.tar.gz
      dest: /opt
      remote_src: yes 